# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQHyozkj-k694nVMksF6v6DuY4R-jfCt
"""

import random

secret_number = random.randint(1, 100)
attempts = 0

print("Welcome to the Number Guessing Game!")
print("I picked a number between 1 and 100.")
print("Can you guess it?")

# Keep looping until user guesses correctly
while True:
    guess_str = input("\nEnter your guess: ")
    guess = int(guess_str)     # convert to integer
    attempts += 1              # count this attempt

    if guess < secret_number:
        print("Too low! Try higher.")
    elif guess > secret_number:
        print("Too high! Try lower.")
    else:
        print(f"\nCorrect! The number was {secret_number}.")
        print(f"You got it in {attempts} attempts!")

        if attempts <= 7:
            print("Excellent! You used binary search thinking.")
        else:
            print("Good try! Hint: always guess the middle.")
        break   # exit the loop